language: python
python:
  - '2.7'
sudo: required

cache:
  pip: true
  directories:
    - api/node_modules
    - website/node_modules

branches:
  only:
    - master

install:
  - nvm install 9.4.0
  - npm install -g serverless
  - cd api && npm install && cd ../website && npm install && cd ../
  - pip install awscli

script:
  - cd api 
  - npm run lint
  - chmod +x ../scripts/api-env-vars.sh && ../scripts/api-env-vars.sh
  - cd ../website && npm run-script ng build -- --prod --aot --configuration=dev
  - cd ../
  - sls --version
  - echo "script finished"
  

deploy:
  - provider: script
    script: chmod +x ./scripts/deploy-api.sh && ./scripts/deploy-api.sh
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    local_dir: website/dist
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key:
      secure: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$AWS_BUCKET"
    on:
      branch: master

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"